[package]
name = "xv6_rust"
version = "0.1.0"
authors = ["Gogo <gogo81745.moe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
bitflags = "1.0"
linked_list_allocator = "0.9"
array-macro = "2.1.0"
cstr_core = "0.2.3"

param_lib = { path = "../../lib/param_lib" }
file_system_lib = { path = "../../lib/file_system_lib" }
file_control_lib = { path = "../../lib/file_control_lib" }