[config]
default_to_workspace = false

[tasks.build_xv6_rust]
script = """
    cargo rustc --package xv6_rust --bin xv6_rust --target riscv64gc-unknown-none-elf \
    -- -C link-arg=-Tbin/xv6_rust/src/ld/kernel.ld -C opt-level=1

    riscv64-unknown-elf-objdump -S target/riscv64gc-unknown-none-elf/debug/xv6_rust > kernel.S
"""

[env]
USER_PROGRAM = "init ls"

[tasks.build_user]
script = """
    for i in ${USER_PROGRAM}
    do
        cargo rustc --package user --target riscv64gc-unknown-none-elf --bin ${i} -- -C opt-level=1 -C link-arg=-Tbin/user/src/ld/user.ld -C link-arg=-N
        riscv64-unknown-elf-strip target/riscv64gc-unknown-none-elf/debug/${i}
    done
"""

[tasks.build_mkfs]
command = "cargo"
args = ["build", "--package", "mkfs"]

[tasks.build_img]
dependencies = ["build_mkfs"]
script = """
    cp user/sh target/riscv64gc-unknown-none-elf/debug/
    target/debug/mkfs fs.img ${USER_PROGRAM} sh
"""

[tasks.build_all]
run_task = [
    { name = ["build_xv6_rust", "build_user", "build_img"] }
]

[tasks.run]
dependencies = ["build_all"]
script = """
    qemu-system-riscv64 \
    -machine virt -bios none \
    -m 128M -smp 3 -nographic \
    -drive file=fs.img,if=none,format=raw,id=x0 \
    -device virtio-blk-device,drive=x0,bus=virtio-mmio-bus.0 \
    -kernel target/riscv64gc-unknown-none-elf/debug/xv6_rust
"""

[tasks.debug]
dependencies = ["build_all"]
script = """
    echo "*** Now run 'gdb' in another window."

    qemu-system-riscv64 \
    -machine virt -bios none \
    -m 128M -smp 3 -nographic \
    -drive file=fs.img,if=none,format=raw,id=x0 \
    -device virtio-blk-device,drive=x0,bus=virtio-mmio-bus.0 \
    -kernel target/riscv64gc-unknown-none-elf/debug/xv6_rust \
    -S -gdb tcp::26000
"""
