[package]
name = "user"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ufmt = "0.1.0"
cstr_core = "0.2.3"

file_control_lib = { path = "../../lib/file_control_lib" }
file_system_lib = { path = "../../lib/file_system_lib" }