[package]
name = "mkfs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = { version = "1.4.0"}

param_lib = { path = "../../lib/param_lib" }
file_system_lib = { path = "../../lib/file_system_lib" }
